"""Omatchy — Omarchy to Hermes Dashboard theme bridge.

Backend API for the Omatchy plugin. Reads the current Omarchy theme,
maps its palette and font to Hermes dashboard theme format, and exposes
the result via GET /api/plugins/omatchy/status.
"""

import tomllib
from pathlib import Path
from typing import Any, Dict, Optional

from fastapi import APIRouter

router = APIRouter()

# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

def _hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))


def _luminance(hex_color: str) -> float:
    r, g, b = _hex_to_rgb(hex_color)
    return 0.299 * r + 0.587 * g + 0.114 * b


def _lighten(hex_color: str, amount: float = 0.2) -> str:
    import colorsys
    r, g, b = _hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    l = min(1.0, l + amount)
    nr, ng, nb = colorsys.hls_to_rgb(h, l, s)
    return f"#{int(nr*255):02x}{int(ng*255):02x}{int(nb*255):02x}"


def _darken(hex_color: str, amount: float = 0.2) -> str:
    import colorsys
    r, g, b = _hex_to_rgb(hex_color)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    l = max(0.0, l - amount)
    nr, ng, nb = colorsys.hls_to_rgb(h, l, s)
    return f"#{int(nr*255):02x}{int(ng*255):02x}{int(nb*255):02x}"


def _rgba(hex_color: str, alpha: float = 1.0) -> str:
    r, g, b = _hex_to_rgb(hex_color)
    return f"rgba({int(r*255)}, {int(g*255)}, {int(b*255)}, {alpha})"


# ---------------------------------------------------------------------------
# Omarchy readers
# ---------------------------------------------------------------------------

def _get_home() -> Path:
    """Return real home even if $HOME points at Hermes profile."""
    import os
    raw = Path.home()
    # If we're inside a Hermes profile home, the *parent* of .hermes/home is the real home
    if str(raw).endswith("/.hermes/home"):
        return raw.parent.parent
    # Also verify via passwd database (most reliable)
    try:
        import pwd
        real = pwd.getpwuid(os.getuid()).pw_dir
        if real and Path(real).is_dir():
            return Path(real)
    except Exception:
        pass
    return raw


def get_current_omarchy_theme() -> tuple[str, Optional[Dict[str, Any]]]:
    """Return (theme_name, colors_dict or None)."""
    home = _get_home()
    name_file = home / ".config/omarchy/current/theme.name"
    if not name_file.exists():
        return "unknown", None

    theme_name = name_file.read_text().strip()

    # Priority: generated current theme → user themes → stock themes
    search_dirs = [
        home / ".config/omarchy/current/theme",
        home / f".config/omarchy/themes/{theme_name}",
        home / f".local/share/omarchy/themes/{theme_name}",
    ]

    # Also broad search: any directory whose name is a prefix of theme_name
    for base in (home / ".config/omarchy/themes", home / ".local/share/omarchy/themes"):
        if base.is_dir():
            for child in sorted(base.iterdir()):
                if child.is_dir() and theme_name.startswith(child.name):
                    candidate = child / "colors.toml"
                    if candidate.exists() and candidate not in [d / "colors.toml" for d in search_dirs if d != base]:
                        search_dirs.append(child)

    for d in search_dirs:
        candidate = d / "colors.toml" if d.is_dir() else d
        if candidate.is_file() and candidate.name == "colors.toml":
            try:
                colors = tomllib.loads(candidate.read_text())
                return theme_name, colors
            except Exception:
                continue

    return theme_name, None


def get_current_font() -> str:
    """Return the active system font from Waybar CSS or Kitty/Ghostty conf."""
    home = _get_home()

    # Primary: Waybar style.css (generated by omarchy-theme-set-templates)
    waybar_css = home / ".config/waybar/style.css"
    if waybar_css.exists():
        for line in waybar_css.read_text().splitlines():
            if "font-family" in line:
                # Extract value between quotes or after colon
                import re
                m = re.search(r'font-family:\s*["\']?([^;"\']+)', line)
                if m:
                    return m.group(1).strip()

    # Fallback: Kitty
    kitty_conf = home / ".config/kitty/kitty.conf"
    if kitty_conf.exists():
        for line in kitty_conf.read_text().splitlines():
            if line.strip().startswith("font_family"):
                return line.split(maxsplit=1)[1].strip().strip('"\'')

    # Fallback: Ghostty
    ghostty_conf = home / ".config/ghostty/config"
    if ghostty_conf.exists():
        for line in ghostty_conf.read_text().splitlines():
            if line.strip().startswith("font-family"):
                return line.split("=")[1].strip().strip('"\'')

    return "ui-monospace, \"SF Mono\", Menlo, Consolas, monospace"


# ---------------------------------------------------------------------------
# Mapping
# ---------------------------------------------------------------------------

def map_omarchy_to_hermes(colors: Dict[str, Any], font: str, theme_name: str) -> Dict[str, Any]:
    bg = colors.get("background", "#1e1e2e")
    fg = colors.get("foreground", "#cdd6f4")
    accent = colors.get("accent", "#89b4fa")
    cursor = colors.get("cursor", accent)

    is_light = _luminance(bg) > 0.5

    # Midground: try cursor first (often a readable accent), else accent
    midground = cursor if cursor != bg else accent
    mid_lum = _luminance(midground)
    if is_light and mid_lum > 0.5:
        midground = _darken(midground, 0.35)
    elif not is_light and mid_lum < 0.5:
        midground = _lighten(midground, 0.35)

    # Ensure contrast against background
    bg_lum = _luminance(bg)
    mid_lum = _luminance(midground)
    if abs(bg_lum - mid_lum) < 0.25:
        midground = _lighten(bg, 0.5) if not is_light else _darken(bg, 0.5)

    warm_glow = _rgba(accent, 0.22)

    # Font stack: use the detected system font as both sans and mono
    # with monospace backups for mono
    font_clean = font.strip()
    if "," not in font_clean:
        font_stack = font_clean
    else:
        font_stack = font_clean

    # If font name contains Mono/MonoLisa/Menlo/Fira Code etc., it's a monospace font
    is_mono_font = any(kw.lower() in font_stack.lower() for kw in (
        "mono", "menlo", "code", "consolas", "courier", "iosevka",
        "hack", "source code", "ibm plex mono", "jetbrains"
    ))

    if is_mono_font:
        font_sans = f'{font_stack}, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif'
        font_mono = f'{font_stack}, ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace'
    else:
        font_sans = f'{font_stack}, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif'
        font_mono = 'ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace'

    return {
        "omarchyTheme": theme_name,
        "palette": {
            "background": {"hex": bg, "alpha": 1.0},
            "midground": {"hex": midground, "alpha": 1.0},
            "foreground": {"hex": fg, "alpha": 0.0},
            "warmGlow": warm_glow,
            "noiseOpacity": 0.8,
        },
        "typography": {
            "fontSans": font_sans,
            "fontMono": font_mono,
            "baseSize": "15px",
            "lineHeight": "1.55",
            "letterSpacing": "0",
        },
        "layout": {
            "radius": "0.5rem",
            "density": "comfortable",
        },
        "layoutVariant": "standard",
        "colorOverrides": {
            "primary": accent,
            "primaryForeground": bg if is_light else fg,
            "accent": accent,
            "accentForeground": bg if is_light else fg,
            "ring": accent,
            "border": _rgba(accent, 0.18),
            "destructive": colors.get("color1", "#ef4444"),
            "success": colors.get("color2", "#22c55e"),
            "warning": colors.get("color3", "#f59e0b"),
        },
    }


# ---------------------------------------------------------------------------
# API routes
# ---------------------------------------------------------------------------

@router.get("/status")
async def omatchy_status():
    """Return the current Omarchy theme mapped to Hermes dashboard format.

    If Omarchy is not installed or no theme is active, returns a fallback
    dark theme so the dashboard stays usable.
    """
    theme_name, colors = get_current_omarchy_theme()
    font = get_current_font()

    if colors is None:
        # Omarchy not installed or theme not found — return a safe fallback
        return {
            "omarchyTheme": theme_name,
            "installed": False,
            "palette": {
                "background": {"hex": "#0a0a0a", "alpha": 1.0},
                "midground": {"hex": "#888888", "alpha": 1.0},
                "foreground": {"hex": "#ffffff", "alpha": 0.0},
                "warmGlow": "rgba(128, 128, 128, 0.22)",
                "noiseOpacity": 0.8,
            },
            "typography": {
                "fontSans": 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
                "fontMono": 'ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace',
                "baseSize": "15px",
                "lineHeight": "1.55",
                "letterSpacing": "0",
            },
            "layout": {"radius": "0.5rem", "density": "comfortable"},
            "layoutVariant": "standard",
            "colorOverrides": {
                "primary": "#7aa2f7",
                "primaryForeground": "#0a0a0a",
                "accent": "#7aa2f7",
                "ring": "#7aa2f7",
                "border": "rgba(122, 162, 247, 0.18)",
                "destructive": "#ef4444",
                "success": "#22c55e",
                "warning": "#f59e0b",
            },
        }

    result = map_omarchy_to_hermes(colors, font, theme_name)
    result["installed"] = True
    return result


@router.get("/hello")
async def omatchy_hello():
    return {"message": "Omatchy bridge is alive", "plugin": "omatchy", "version": "1.0.0"}
